lib/shortr_web/router.ex
defmodule ShortrWeb.Router do
  use ShortrWeb, :router

  import ShortrWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ShortrWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ShortrWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/l/listings", LinkLive.Index, :index
    live "/l/new", LinkLive.Index, :new
    live "/l/:id/edit", LinkLive.Index, :edit
    live "/l/:id", LinkLive.Index, :show
  end

  scope "/", ShortrWeb do
    pipe_through :browser
    get "/", MarketingController, :index
    get "/s/:id", LinkController, :get_and_redirect
  end

  # Other scopes may use custom stacks.
  # scope "/api", ShortrWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: ShortrWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", ShortrWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ShortrWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ShortrWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/shortr_web/live/link_live/form_component.ex
defmodule ShortrWeb.LinkLive.FormComponent do
  use ShortrWeb, :live_component

  alias Shortr.Links
  alias Shortr.Accounts

  @impl true
  def update(%{link: link} = assigns, socket) do
    changeset = Links.change_link(link)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"link" => link_params}, socket) do
    changeset =
      socket.assigns.link
      |> Links.change_link(link_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"link" => link_params}, socket) do
    save_link(socket, socket.assigns.action, link_params)
  end

  defp save_link(socket, :edit, link_params) do
    case Links.update_link(socket.assigns.link, link_params) do
      {:ok, _link} ->
        {:noreply,
         socket
         |> put_flash(:info, "Link updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_link(socket, :new, link_params) do
    user = Accounts.get_user!(socket.assigns.current_user_id)

    case Links.create_link(user, link_params) do
      {:ok, _link} ->
        {:noreply,
         socket
         |> put_flash(:info, "Link created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/shortr_web/live/link_live/index.ex
defmodule ShortrWeb.LinkLive.Index do
  use ShortrWeb, :live_view

  alias Shortr.Links
  alias Shortr.Links.Link
  alias Shortr.Accounts

  @impl true
  def mount(_params, %{"user_token" => user_token}, socket) do
    user = Accounts.get_user_by_session_token(user_token)

    new_assigns =
      socket
      |> assign(:links, Links.list_links(user.id))
      |> assign(:current_user_id, user.id)

    {:ok, new_assigns}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Link")
    |> assign(:action_label, "Save change")
    |> assign(:link, Links.get_link!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Link")
    |> assign(:action_label, "Shorten link")
    |> assign(:link, %Link{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Links")
    |> assign(:link, nil)
  end

  defp apply_action(socket, :show, %{"id" => id}) do
    socket
    |> assign(:page_title, "Show Link")
    |> assign(:link, Shortr.Metrics.list_visits(id))
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    link = Links.get_link!(id)
    {:ok, _} = Links.delete_link(link)

    {:noreply, assign(socket, :links, Links.list_links(socket.assigns.current_user_id))}
  end
end

lib/shortr_web/live/live_helpers.ex
defmodule ShortrWeb.LiveHelpers do
  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.link_index_path(@socket, :index)}>
        <.live_component
          module={ShortrWeb.LinkLive.FormComponent}
          id={@link.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.link_index_path(@socket, :index)}
          link: @link
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="modal modal-open fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="modal-box relative bg-slate-100 dark:bg-slate-900"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch to: @return_to,
            id: "close",
            class: "btn btn-square absolute right-2 top-2",
            phx_click: hide_modal() do
          %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
          <% end %>
        <% else %>
          <a id="close" href="#" class="btn btn-square absolute right-2 top-2" phx-click={hide_modal()}>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
          </a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content")
  end

  def drawer(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div class="drawer drawer-end">
    <div class="drawer-side">
      <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end
end

lib/shortr_web/live/link_live/form_component.html.heex
<div class="space-y-4">
  <h2 class="text-xl sm:text-2xl font-bold text-slate-900 dark:text-slate-200"><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="link-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">

    <%= label f, :url %>
    <%= text_input f, :url, type: "url", class: "input input-bordered w-full" %>
    <label class="label">
      <%= error_tag f, :url %>
    </label>

    <div class="mt-4 text-right">
      <%= submit @action_label, phx_disable_with: "Generating...", class: "btn btn-primary" %>
    </div>
  </.form>
</div>

lib/shortr_web/live/link_live/index.html.heex
<div class="flex justify-between my-4">
  <h1 class="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight dark:text-slate-200">Listing Links</h1>
  <%= if !Enum.empty?(@links) do %>
    <%= live_patch "New Link", to: Routes.link_index_path(@socket, :new), class: "btn btn-primary" %>
  <% end %>
</div>

<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.link_index_path(@socket, :index)}>
    <.live_component
      module={ShortrWeb.LinkLive.FormComponent}
      id={@link.hash || :new}
      title={@page_title}
      action={@live_action}
      link={@link}
      action_label={@action_label}
      return_to={Routes.link_index_path(@socket, :index)}
      current_user_id={@current_user_id}
    />
  </.modal>
<% end %>

<%= if @live_action in [:show] do %>
  <.modal return_to={Routes.link_index_path(@socket, :index)}>
    <div class="stats shadow">
      <div class="stat">
        <div class="stat-title">Total Page Views</div>
        <div class="stat-value"><%= Enum.count(@link.views) %></div>
        <div class="stat-desc flex items-center">
          <%= @link.hash %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M13 7l5 5m0 0l-5 5m5-5H6" />
          </svg>
          <b><%= @link.url %></b>
        </div>
      </div>
    </div>
  </.modal>
<% end %>

<%= if Enum.empty?(@links) do %>
  <div class="hero my-10">
    <div class="hero-content text-center">
      <div class="max-w-md">
        <h1 class="text-5xl font-bold"><span aria-label="hand wave" role="img">👋</span> Welcome to Shortr </h1>
        <p class="py-4 text-lg">This is a simple link shortener app written in Elixir, built on Pheonix and uses Tailwind and DaisyUI for styling. Create your first shortened link to get started!</p>
        <%= live_patch "Shorten your first link", to: Routes.link_index_path(@socket, :new), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% else %>
  <div class="relative bg-slate-50 rounded-xl overflow-hidden dark:bg-slate-800/25">
    <div class="relative rounded-xl overflow-auto border border-slate-100 dark:border-slate-700 ">
      <div class="overflow-hidden my-8">
        <table class="table-auto w-full border-collapse">
          <thead>
            <tr>
              <th class="border-b dark:border-slate-600 font-medium p-4 pt-0 pb-3 text-slate-700 dark:text-slate-200 text-left">Short Hash</th>
              <th class="border-b dark:border-slate-600 font-medium p-4 pt-0 pb-3 text-slate-700 dark:text-slate-200 text-left">Link</th>
              <th class="border-b dark:border-slate-600 font-medium p-4 pt-0 pb-3 text-slate-700 dark:text-slate-200 text-left">Actions</th>
            </tr>
          </thead>
          <tbody id="links" class="bg-white dark:bg-slate-800">
            <%= for link <- @links do %>
              <tr id={"link-#{link.hash}"}>
                <td class="border-b border-slate-100 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-300"><%= link.hash %> <%= link "Visit", to: Routes.link_path(@socket, :get_and_redirect, link.hash), target: "_blank", class: "btn btn-xs" %></td>
                <td class="border-b border-slate-100 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-300"><%= link.url %></td>
                <td class="border-b border-slate-100 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-300">
                  <div class="btn-group">
                    <%= live_patch "Show", to: Routes.link_index_path(@socket, :show, link), class: "btn btn-sm btn-accent btn-outline" %>
                    <%= live_patch "Edit", to: Routes.link_index_path(@socket, :edit, link), class: "btn btn-sm btn-warning btn-outline" %>
                    <%= link "Delete", to: "#", phx_click: "delete", phx_value_id: link.hash, data: [confirm: "Are you sure?"], class: "btn btn-sm btn-error btn-outline" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>